package mediathek.gui.dialog;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import mediathek.config.Konstanten;
import mediathek.config.MVConfig;
import mediathek.daten.DatenDownload;
import mediathek.tool.EscapeKeyHandler;
import net.miginfocom.layout.AC;
import net.miginfocom.layout.CC;
import net.miginfocom.layout.LC;
import net.miginfocom.swing.MigLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MeldungDownloadfehler extends JDialog {
    private final Timer countdownTimer;

    public MeldungDownloadfehler(Frame parent, String text, DatenDownload datenDownload) {
        super(parent, false);
        initComponents();

        setFocusableWindowState(false);
        setFocusable(false);
        if (parent != null) {
            setLocationRelativeTo(parent);
        }

        EscapeKeyHandler.installHandler(this, this::dispose);

        jTextArea1.setText(text);
        jTextFieldTitel.setText(datenDownload.arr[DatenDownload.DOWNLOAD_TITEL]);
        jButtonOk.addActionListener(_ -> dispose());

        //start the countdown...
        countdownTimer = new Timer(0, new CountdownAction());
        countdownTimer.setRepeats(true);
        countdownTimer.start();

        pack();
    }

    @Override
    public void setVisible(boolean vis) {
        if (Boolean.parseBoolean(MVConfig.get(MVConfig.Configs.SYSTEM_DOWNLOAD_ERRORMSG))) {
            super.setVisible(vis);
        } else {
            dispose();
        }
    }

    /**
     * Implements the countdown based on Swing Timer for automatic placement on EDT.
     */
    private class CountdownAction implements ActionListener {

        private int w = Konstanten.DOWNLOAD_ERROR_DISPLAY_DURATION;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (w > 0) {
                jLabelTime.setText(w + " s");
                if (countdownTimer != null) {
                    countdownTimer.setDelay(1000);
                }
            } else {
                MeldungDownloadfehler.this.dispose();
            }
            w--;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner non-commercial license
    private void initComponents() {
        var jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        var jLabelIcon = new JLabel();
        var jLabel2 = new JLabel();
        jTextFieldTitel = new JTextField();
        jLabelTime = new JLabel();
        jButtonOk = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Downloadfehler");
        var contentPane = getContentPane();
        contentPane.setLayout(new MigLayout(
            new LC().insets("dialog").hideMode(3).gridGap("rel", "rel"),
            // columns
            new AC()
                .fill().gap()
                .grow().fill(),
            // rows
            new AC()
                .fill().gap()
                .grow().fill().gap()
                .fill()));

        //======== jScrollPane1 ========
        {

            //---- jTextArea1 ----
            jTextArea1.setEditable(false);
            jTextArea1.setColumns(20);
            jTextArea1.setLineWrap(true);
            jTextArea1.setRows(4);
            jTextArea1.setWrapStyleWord(true);
            jScrollPane1.setViewportView(jTextArea1);
        }
        contentPane.add(jScrollPane1, new CC().cell(1, 1).push().grow());

        //---- jLabelIcon ----
        jLabelIcon.setIcon(new FlatSVGIcon("icons/fontawesome/triangle-exclamation.svg", 32, 32));
        jLabelIcon.setVerticalAlignment(SwingConstants.TOP);
        contentPane.add(jLabelIcon, new CC().cell(0, 0, 1, 3).alignY("top"));

        //---- jLabel2 ----
        jLabel2.setText("Filmtitel:");
        contentPane.add(jLabel2, new CC().split(2).cell(1, 0));

        //---- jTextFieldTitel ----
        jTextFieldTitel.setEditable(false);
        contentPane.add(jTextFieldTitel, new CC().pushX().growX());

        //---- jLabelTime ----
        jLabelTime.setText("0 s");
        contentPane.add(jLabelTime, new CC().cell(1, 2));

        //---- jButtonOk ----
        jButtonOk.setText("Ok");
        contentPane.add(jButtonOk, new CC().cell(1, 2).alignX("center").growX(0));
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner non-commercial license
    private JTextArea jTextArea1;
    private JTextField jTextFieldTitel;
    private JLabel jLabelTime;
    private JButton jButtonOk;
    // End of variables declaration//GEN-END:variables
}
